### ISSUE TITLE
502 An error occured with your deployment.

### ISSUE THREAD

**Issue by darrachequesne** [zeit/now-cloud#17]
Is there any way to debug that error:

![image](https://cloud.githubusercontent.com/assets/13031701/25200699/8ec28922-254f-11e7-9a6c-623a27e7e69f.png)

https://now-examples-slackin-fwxlbrkiuz.now.sh/

Is it related to the deployment going to sleep? (https://zeit.co/docs/deployment-types/node#deployment-inactivity)

Edit: the page is served with a HTTP 200 status though, that's weird.

**Comment by BurntCaramel** [comment]
Yeah I see something similar, yet `now logs` does not list anything out of order.

**Comment by jamo** [comment]
Based on the status of `now-examples-slackin-fwxlbrkiuz:now:sh` it had been crashlooping and the system had given up trying to start it up. I've now manually restarted it and it might just work a while if the crashlooping was time related...
