### ISSUE TITLE
Request: add example of accessing environment variables from Docker

### ISSUE THREAD

**Issue by Sequoia** [zeit/now-cloud#23]
I wish to pass a password for redis in a docker container via `--requirepass $SECRET` on redis startup.

From [docs](https://zeit.co/docs/features/env-and-secrets#tips-&-tricks):

> How about other programming languages? The same mechanism applies to any project with a Dockerfile. The variables you include will be available to your RUN and CMD instructions.

How does one access these environment variables? I am a bit of a docker novice so apologies if this is obvious, but looking around I did not find an obvious solution. Is this the recommended pattern? https://github.com/moby/moby/issues/5509#issuecomment-45243772

An example of how to get from `now secret` to accessing env var in docker `CMD` instruction would be greatly appreciated.

**Comment by sergiodxa** [comment]
In your `now.json` file add your environment variables using secrets (`@secret-key`), then the command you run with `CMD` should have access to the variables.

That's what worked for me here -> https://github.com/platzi/now-course/tree/master/api

**Comment by Sequoia** [comment]
Here's what I came up with (haven't tested on `now` but it works with `docker run --env` so I assume it works on now too 😅 )

```Dockerfile
FROM redis
CMD [ "sh", "-c", "redis-server --requirepass $REDIS_PASS"]
```

Per the [docker docs](https://docs.docker.com/engine/reference/builder/#cmd):

> **Note**: Unlike the *shell* form, the exec form does not invoke a command shell. This means that normal shell processing does not happen. For example, `CMD [ "echo", "$HOME" ]` will not do variable substitution on `$HOME`. If you want shell processing then either use the shell form or execute a shell directly, for example: `CMD [ "sh", "-c", "echo $HOME" ]`. When using the exec form and executing a shell directly, as in the case for the shell form, it is the shell that is doing the environment variable expansion, not docker.

This part of the `now` docs were confusing because they seemed to suggest ENV vars *were* available directly to the `CMD` command (not just the command that `CMD` executes, e.g. `sh` or `python`)

> How about other programming languages? The same mechanism applies to any project with a Dockerfile. The variables you include will be available to your RUN and CMD instructions.

For most cases this doesn't matter, but a tool like `redis` **must** have configuration passed in via shell args or in a `redis.conf` file, it **cannot** read configuration from environment vars (as mysql etc. can). So you **have to** access env vars on startup, i.e. in Dockerfile (or put them in a startup script).

**Comment by sergiodxa** [comment]
1. You should not run Redis on Now, it's for HTTP services, not databases because it's immutable. Even if you use it for PubSub.
2. In my experience with Docker in Now you can access to ENV variables inside any service you run with `CMD`. I just deployed a docker container who run a Node.js GraphQL API using `CMD ["npm", "start"]` and it has access to the DB user, pass, name and host via secrets via environment variables.
