### ISSUE TITLE
`yarn.lock` file is stale! ... Please regenerate by running `yarn`.

### ISSUE THREAD

**Issue by paulirish** [zeit/now-cloud#25]
My package has a devDep on of [cypress-cli](https://github.com/cypress-io/cypress-cli). It has a github dependency:

```js
    "xvfb": "cypress-io/node-xvfb",
```

My lockfile's entry for it looks like this:
```ini
"xvfb@github:cypress-io/node-xvfb":
  version "0.3.0"
  resolved "https://codeload.github.com/cypress-io/node-xvfb/tar.gz/22e3783c31d81ebe64d8c0df491ea00cdc74726a"
```

But now appears to have a problem with this dependency. When starting to deploy it errors:

```
06/04 05:45 PM (11m)    npm install
06/04 05:45 PM (11m)    ✓ Using "yarn.lock"
06/04 05:45 PM (11m)    ⧗ Installing 7 main dependencies…
06/04 05:45 PM (11m)    `yarn.lock` file is stale! Missing entry for "xvfb@cypress-io/node-xvfb". Please regenerate by running `yarn`.
```

AFAIK, this is due to a bug in your `ace` as this is how the latest yarn handles these dependencies in the lockfile.

**Comment by matheuss** [comment]
Thank you for reporting @paulirish – a fix will be out very soon :v:

**Comment by matheuss** [comment]
Fixed and deployed 👌 Could you confirm it works @paulirish?

**Comment by paulirish** [comment]
fix confirmed. thanks for the quick work. :)
