### ISSUE TITLE
Allow to set `--single` in static deployments

### ISSUE THREAD

**Issue by sergiodxa** [zeit/now-cloud#26]
Right now static deployment's aren't really useful for SPA since we can't use the `--single` parameter used by [serve](https://github.com/zeit/serve) to only send the `index.html` file without creating a custom npm deployment.

It should be useful to be able to configure that parameter from the `now.json` file. Maybe using `"type": "static-single"` or another key like `"static": { "single": true }` to configure the serve params.

**Comment by babakness** [comment]
+1, This only makes sense. Obviously `/#/` style urls will work but not ideal

**Comment by SilentCicero** [comment]
+1

**Comment by TV-productions** [comment]
Any update on this? Or can this be fixed by specifying some redirects?

**Comment by sergiodxa** [comment]
This is not fixed with new static deployments.
