### ISSUE TITLE
`/home/nowuser/autopmap: line 18: errcho: command not found`

### ISSUE THREAD

**Issue by HemalR** [zeit/now-cloud#28]
My deployment keeps erroring out after approx 1ish hours up with a logged message of:

`/home/nowuser/autopmap: line 18: errcho: command not found`

Any idea what this might be and what the fix might be?

Thanks!

**Comment by OlliV** [comment]
I'm not sure why it breaks like that but either your deployment isn't listening on any port or it's listening on multiple ports.

**Comment by HemalR** [comment]
Ah ok - I think I must have not bound it properly - have made a modification to the code and deployed. Will revisit if still an issue.

Thanks for the pointer!
