### ISSUE TITLE
Use of `files` in `now.json` results in `Error: Cannot find module '/home/nowuser/src/index.js'` during deployment

### ISSUE THREAD

**Issue by aresnick** [zeit/now-cloud#29]
This seems to be the same as [closed issue #265 at `now-cli`](https://github.com/zeit/now-cli/issues/265).  It doesn't seem to have been migrated to `now-cloud`.

I'm trying to set up a deployment of a static site, generated by Jekyll, and served up _via_ `now` using a minimal `express` application.

Jekyll outputs its static site into a `_site` folder, which I've included in my `.gitignore`.  My understanding from [this blog post referencing the `files` array](https://zeit.co/blog/now-json#`files`-(array)) is that the `files` array can contain files or directories which should be deployed, even if they are included in a `.gitignore`.

Is there an existing workaround for this, or am I missing something?  It'd be very useful for projects, e.g., combining a static site and API functionality.

A minimal example can be found [here](https://gist.github.com/aresnick/7dcb05ab219d4bc9ac5abad1eba8d25a), though you'll need to add a `_site` folder with `index.html` in it to test.  A zip file containing such a setup can be found [here](https://gist.github.com/aresnick/7dcb05ab219d4bc9ac5abad1eba8d25a).

The error output I see when I run `now` is:
```
❯ now
> Deploying ~/Desktop/now-files-error under aresnick
> Using Node.js 8.1.2 (default)
> Ready! https://now-files-error-mpfsdkdpwr.now.sh (copied to clipboard) [2s]
> Synced 2 files (271B) [2s] 
> Initializing…
> Building
> ▲ npm install
> ⧗ Installing 1 main dependency…
> ✓ Installed 42 modules [8s]
> ▲ npm start
> > now-files-error@ start /home/nowuser/src
> > node index.js
> module.js:487
>     throw err;
>     ^
> Error: Cannot find module '/home/nowuser/src/index.js'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:575:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! now-files-error@ start: `node index.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the now-files-error@ start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-07-07T02_37_48_059Z-debug.log
> Deployment complete!
```

Thanks for your help!

**Comment by sdll** [comment]
The same problem occurs when a node.js module with the non-empty `files` parameter is deployed.

**Comment by 100ideas** [comment]
:wave: Hi @aresnick! Say, did you develop a work-around or switch to a different tool?

**Comment by aresnick** [comment]
@100ideas Hey!  I switched to using Netlify—

**Comment by TooTallNate** [comment]
The `files` array is an explicit whitelist, so you need to include `index.js` in it for it to be uploaded as part of your deployment. Sorry for not explaining when the issue was first created.

**Comment by 100ideas** [comment]
@aresnick lol me too, I am helping my sister set up an rmarkdown / blogdown / r-studio toolchain for her academic portfolio/blog (public health epidemiology). I still use zeit/now for small personal projects however. Cheers.

**Comment by rsweetland** [comment]
This still appears to be a bug. Any value in the `files` array (in package.json or now.json) results in the above error. When I explicitly include index.js in the files array, it still fails to find other required modules. 

It appears that the `files` behaves more like the normal, npm `files` array, excluding all other files from the deploy except those explicitly listed in the array. If this is the case, maybe it's just a matter of updating the docs?

Fortunately [this workaround](https://github.com/zeit/now-cli/issues/157#issuecomment-284269419) worked for me.  (In short: Add `!dist` or whatever you are force-deploying to `.npmignore`.) It still works even it also being listed in `.gitignore`.

**Comment by rsweetland** [comment]
Update: It does appear the `now.files` array works just like the [npm files array](https://github.com/npm/npm/wiki/Files-and-Ignores), _excluding all other files from the deploy except those listed in the array_.

I tested this by copying my `now.files` array to a root-level `files` array in `package.json`, then running [npm pack](https://docs.npmjs.com/cli/pack). The contents of the tarball appear to be the same as those that were deployed. 

Maybe the docs could be changed from: 
> A list of files and directories to be force-uploaded to the deployment (even if they're ignored by .gitignore).

To: 
> A list of _only_ the files and directories you to deploy. (Overrides .gitignore)

I could see advantages to implementing this either way.
