### ISSUE TITLE
Deployment repeatedly restarting without visible errors

### ISSUE THREAD

**Issue by ml9951** [zeit/now-cloud#3]
I have a Docker deployment that keeps continually restarting.  I'm using `now-logs` to redirect the logs from my application.  Everything seems to be starting up just fine, but then it restarts itself without any indication why.

![Imgur](http://i.imgur.com/So08mvg.png)

Logs:

```
Listening at http://localhost:8080

Listening at http://localhost:8080

Listening at http://localhost:8080
...
```

**Comment by ml9951** [comment]
This is still a problem.

**Comment by OlliV** [comment]
Can you send me a DM in slack?
