### ISSUE TITLE
Frequent 503, "The deployment is currently unavailable".

### ISSUE THREAD

**Issue by donmccurdy** [zeit/now-cloud#30]
I'm regularly (once a week or so) seeing the `503 | The deployment is currently unavailable` message, after my site hangs for 30s or more. This is a public webpage, and I have to assume it is affecting users as well, but am not sure how to get help from the logs.

Given that (1) I'm on the Premium plan, and (2) this is a static deployment, these errors are very much unexpected. Is this related to the new scaling feature, and I should be setting a minimum number of instances? Is there documentation about the "sleep" feature, and how to productionize a service? My logs also have messages along the lines of  `No open port found`, but again it's a static deployment so I don't know what to do with that.

Here is my configuration: https://github.com/donmccurdy/three-gltf-viewer/blob/master/package.json

Thanks!

**Comment by OlliV** [comment]
I can't tell for sure what's wrong but I'd suggest setting a minimum scale. For the `No open port found`, is the app particularly slow to start? If the deployment is really just about serving static data I'd also suggest you to use our static deployments feature https://zeit.co/blog/unlimited-static

**Comment by donmccurdy** [comment]
@OlliV thanks, I'll try setting minimum scale.

Hm, I had seen that page and assumed that setting `"start": "serve"` *was* the static deployments feature. That's just running a Node.js instance, then, and I need to be deplying with `now --static` explicitly?

**Comment by OlliV** [comment]
If you have no `package.json` it should be automatic but you can always deploy it as static explicitly by giving `--static`.

**Comment by donmccurdy** [comment]
Thanks! I misunderstood that bit; using `now --static` seems to work.
