### ISSUE TITLE
typescript files in source viewer shown as video

### ISSUE THREAD

**Issue by kandros** [zeit/now-cloud#33]
`.ts` files are displayed as videos instead of code

<img width="1254" alt="schermata 2017-08-21 alle 22 29 04" src="https://user-images.githubusercontent.com/4562878/29536996-4373f9ba-86c0-11e7-8cd5-93670fc10d46.png">

**Comment by nkzawa** [comment]
Thanks for the report. We're going to fix this asap.

**Comment by nkzawa** [comment]
Fixed!
