### ISSUE TITLE
Team page url incorrect

### ISSUE THREAD

**Issue by vjpr** [zeit/now-cloud#34]
![screen shot 2017-08-31 at 10 45 15 am](https://user-images.githubusercontent.com/281413/29914833-2f2ef244-8e3a-11e7-883c-7268cfbccf62.png)

From support:

> The teams URL is zeit.co/teams/:slug not zeit.co/:slug.

**Comment by sergiodxa** [comment]
cc @evilrabbit

**Comment by TooTallNate** [comment]
Thank you for the report @vjpr. This is fixed now!
