### ISSUE TITLE
Bump built-in serve version

### ISSUE THREAD

**Issue by nulltask** [zeit/now-cloud#4]
I still need workaround for that issue: https://github.com/zeit/serve/pull/109

Please consider to upgrade built-in serve module.

**Comment by leo** [comment]
https://github.com/zeit/now-cli/commit/797cdd83084f5bb05f94e9a9dd25a31d92464469

**Comment by leo** [comment]
Released in: https://github.com/zeit/now-cli/releases/tag/4.6.0

**Comment by nulltask** [comment]
@leo 👍
