### ISSUE TITLE
IP address to whitelist in MongoDB Cloud

### ISSUE THREAD

**Issue by luislobo** [zeit/now-cloud#41]
MongoDB Cloud offers a cloud service that does not work if you don't configure the IP addresses that will connect to their services (unless you just leave it open to ANY address, something you will not want).

Which IP address/es should be configured so that they can be whitelisted?

**Comment by sergiodxa** [comment]
The IP addresses of Now deployments are too dynamic and for that reason we don't provide a list of them.

Our recommendation when connecting to external services (eg. a database) is to use a strong password and SSL.

**Comment by shawninder** [comment]
@sergiodxa To be clear, you recommend I allow access from everywhere by adding 0.0.0.0/0 to my IP whitelist and relying on password proteciton?

**Comment by slorenzo** [comment]
Could it generate some security issues?

**Comment by luislobo** [comment]
@rauchg Are there any plans or alternative to this issue, besides opening the database to the world?

**Comment by kidandcat** [comment]
You should not depend on IPs, it is not that secure at all. If you cannot configure any other thing, then allow any IP 0.0.0.0 and use a strong password as suggested before, this is not less secure than any of your logins that only use user/password. 

PD: use 15 or more characters on that password.
