### ISSUE TITLE
Memory restrictions in paid plans

### ISSUE THREAD

**Issue by russiann** [zeit/now-cloud#45]
I saw in this issue:
https://github.com/zeit/now-cli/issues/261
that the max memory of each paid plan is 1GB.
But what if my application needs more than 1GB?

**Comment by tuckerconnelly** [comment]
Yeah need to know what the CPU/Memory is of each instance and if we can increase, have some more resource-intensive deployments

**Comment by sergiodxa** [comment]
@tuckerconnelly those limits are correct, at the moment is not possible to configure it.
