### ISSUE TITLE
Multiple Ports in Docker Deployment

### ISSUE THREAD

**Issue by lmachens** [zeit/now-cloud#48]
Hey, I have an application which needs to open multiple ports.
One port for the http/https and another port for the api. 
In https://zeit.co/docs/deployment-types/docker#port-selection it says `Your server code can expose a HTTP service on any port of your choice (not multiple ones).`. Does it mean I can not expose additional ports? Right now I expose the port with `docker run -p 11011:11011 ....`.
Is it possible to pass arguments to docker?
And what happens when I expose the ports in the Dockerfile?

**Comment by sergiodxa** [comment]
Hey.

> Does it mean I can not expose additional ports?

Is not possible to expose multiple ports from a Now deployment.

> Is it possible to pass arguments to docker?

At the moment is not possible.

> And what happens when I expose the ports in the Dockerfile?

We will detect the first exposed port and wait for an HTTP or WebSocket service to start running there, if it never happens we will timeout and mark the deployment as with an error. If it starts one of those services we will redirect all the traffic from HTTPS or WSS to the service on that port.
