### ISSUE TITLE
Public IP address for A record

### ISSUE THREAD

**Issue by nulltask** [zeit/now-cloud#5]
I can't point website hosting on now.sh to zone apex because of my DNS service (Route 53) doesn't support custom alias records. Do you have any plans to provide public IP address for A records?

**Comment by OlliV** [comment]
I don't think it will ever happen for IPv4 at least.

**Comment by TooTallNate** [comment]
I wrote about doing this with an bash script and cronjob: https://n8.io/pseudo-alias-with-google-domains-dns/

It's been working for months for me to update n8.io domain name.

**Comment by DriesVandermeulen** [comment]
@TooTallNate your post seems to be offline. 

We are also using Route 53 as our main DNS Service and switching to the Zeit name servers is just not an option for us. We love to use Now for our main website, but the root apex issue is really blocking.

Can you elaborate on the potential work around you had in your post?

**Comment by dohomi** [comment]
I am looking for a solution as well. @DriesVandermeulen did you resolve your issue somehow?

**Comment by OlliV** [comment]
Actually Route 53 supports alias records, you can create them by creating an A record and then there was an option to make it an alias instead. I can't recall right now how it exactly looked like but it's possible.

**Comment by matheuss** [comment]
👌 
![image](https://user-images.githubusercontent.com/4721750/36624803-dafb0430-18f2-11e8-87bb-e7f48acaf4ae.png)

**Comment by ababkov** [comment]
@matheuss have just tried this an unfortunately it doesn't actually seem to work. Target you're pointing to HAS to be an AWS resource.

**Comment by HemalR** [comment]
What @ababkov said. Was the proposed solution actually tested?
