### ISSUE TITLE
Can't access environment variables inside Dockerfile

### ISSUE THREAD

**Issue by jmcmullen** [zeit/now-cloud#50]
When accessing environment variables inside my dockerfile before CMD they are undefined.
This is an issue for me because I need to use environment variables to build my app not just when it's started.

According to the [docs](https://zeit.co/docs/features/env-and-secrets#tips-&-tricks), environment variables can be done inside RUN but I couldn't access them there either.

Example Dockerfile:
```
FROM node:8.11.1-alpine
RUN apk update && apk upgrade
RUN apk add git

# Set up node
RUN mkdir -p /usr/src/app
COPY . /usr/src/app/
WORKDIR /usr/src/app
RUN yarn install

# Set environment variables
ENV APP_REGION ${APP_REGION}
ENV NODE_ENV ${NODE_ENV}

# Build app source
RUN yarn build

EXPOSE 3000
CMD [ "yarn", "start" ]
```

**Comment by develomark** [comment]
I've also just discovered this issue.

**Comment by sergiodxa** [comment]
This is now possible with the usage of build envs
> https://zeit.co/blog/build-env
