### ISSUE TITLE
Docker instance restarts when using PM2 on v2

### ISSUE THREAD

**Issue by kirkness** [zeit/now-cloud#65]
Hello! Just moved my app from v1 to v2 and now it struggles to start. I've created a simple example of the problem here: https://github.com/kirkness/zeit-v2-docker

Essentially it seems that running in Docker with pm2-runtime on v2 cloud the app process will terminate with a SIGINT every minute or so. Moving back to v1, or running the same app on v2 with `node app.js` the app runs fine.

**Comment by simsketch** [comment]
I cloned your repo and it ran just fine in either v1 or v2, unless I did something wrong? have you tried from another machine? i was having an issue and deploying from another machine worked for me for some reason.

**Comment by simsketch** [comment]
v1 https://restarting-xwmojjgkou.now.sh/ https://zeit.co/simsketch/restarting/xwmojjgkou
v2 https://restarting-ngckjqmsof.now.sh/ https://zeit.co/simsketch/restarting/ngckjqmsof

**Comment by kirkness** [comment]
Thanks @simsketch - Ive now done a little bit more research into what `v2` really means I think its making sense.
