### ISSUE TITLE
Error: Cannot find module './routes'

### ISSUE THREAD

**Issue by simsketch** [zeit/now-cloud#67]
I have my project working locally with no issue, but when I try to `now` deploy, it gets hung up on  `require('./routes')(app);`

i tried removing `main` from `package.json` and adding a `build` script but it seems like nothing i do is having an effect.

my `routes/index.js` file looks like this.

```
const fs = require('fs');
const path = require('path');

module.exports = (app) => {
  // API routes
  fs.readdirSync(__dirname + '/api/').forEach((file) => {
    require(`./api/${file.substr(0, file.indexOf('.'))}`)(app);
  });
};
```

Here is the full error
```
▲ Storing image (21.9M)
> Build completed
> Verifying instantiation in iad1
> [0]     ^
> [1] internal/modules/cjs/loader.js:582
> [2]     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
> [2]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
> [2] Error: Cannot find module './routes'
> [2]     at Object.<anonymous> (/usr/src/server.js:13:1)
> [2]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
> [2]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
```
i started this with the demo node-express Docker cloud v2 code and just added some routes and a static root html file...again, everything works perfectly on my local. here is my package.json

```
{
  "name": "node-express",
  "dependencies": {
    "connect-history-api-fallback": "^1.5.0",
    "cors": "^2.8.4",
    "express": "^4.16.3",
    "fs": "0.0.1-security",
    "mongoose": "^5.3.6"
  },
  "scripts": {
    "build": "node server.js"
  },
  "license": "MIT"
}
```

**Comment by kidandcat** [comment]
Try with a Dockerfile, it seems to have more flexibility, here you have a demo:
https://codesandbox.io/s/qx0xvxr2ow

**Comment by ezito** [comment]
Yes I originally tried in Docker mode...also tried again now... but still gets the same error.

**Comment by ezito** [comment]
This is what my Dockerfile looks like

https://github.com/zeit/now-examples/blob/master/node-express/Dockerfile

**Comment by simsketch** [comment]
Not sure what I changed to make it work but I tried from my Windows machine and had better luck. 

one thing that may have helped was making sure routes was below these two lines

```
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
require('./routes')(app);
```

Thanks for your help...I'm enjoying the performance boost with my new Docker v2 instance compared to my old Now npm deployment.

closing.
