### ISSUE TITLE
Deployment showing directory listing

### ISSUE THREAD

**Issue by mikefrancis** [zeit/now-cloud#74]
Hi there,

I have a repo which when I run `npm run dev` (or `npm run build && npm run start`), it works locally, however when I run `now` to deploy and visit the deployment URL, I get the directory listings for the repo?

https://mikefrancisgithubio-g2wfh6099.now.sh

I'm not sure if this is an issue with the `now-cli` or `now-cloud` or indeed my own setup, but any help would be appreciated!

**Comment by mikefrancis** [comment]
I think it might be a problem with my account, I've just cloned and deployed the example `with-styled-components` example, getting the same directory listings:

https://with-styled-components-9885qo33q.now.sh

What do I do? 😅

**Comment by mikefrancis** [comment]
Argh ok, this was an issue with updating to Now 2.0 - have downgraded an everything is back to normal now.

I'm a tiny bit gutted as the reason I switched from Netlify over to Now was HTTP/2 support on a throw-something-together-and-deploy-it platform, but now that doesn't seem to be the case 😢

**Comment by paulogdm** [comment]
Hello Mike! Please, let me know if I can assist you with your code to deploy it to now v2: [zeit.co/chat](zeit.co/chat)

**Comment by aawalker238** [comment]
I've run into the same issue and I can't resolve it. I've tried various things. This is a head scratcher for me.

**Comment by paulogdm** [comment]
Could you elaborate? I can help if you show some code...

**Comment by paulogdm** [comment]
Unlikely. Maybe you deployed in a folder instead of the root with `now.json`

**Comment by MuddyBootsCode** [comment]
My project is doing the same thing. I'm on the most current version of NOW CLI and designated version two in the now.json and it's only serving the files. Removed version 2 from now.json and it worked fine.

**Comment by paulogdm** [comment]
Can you show your `now.json`?

**Comment by MuddyBootsCode** [comment]
# Current version
{
  "build": {
    "env": {
      "NEO4J_URI": "@neo4j_uri",
      "NEO4J_USER": "@neo4j_user",
      "NEO4J_PASSWORD": "@neo4j_password",
      "GRAPHQL_LISTEN_PORT": "@graphql_listen_port"
    }
  }
}

# Previous Version
{
 "version": 2
  "build": {
    "env": {
      "NEO4J_URI": "@neo4j_uri",
      "NEO4J_USER": "@neo4j_user",
      "NEO4J_PASSWORD": "@neo4j_password",
      "GRAPHQL_LISTEN_PORT": "@graphql_listen_port"
    }
  }
}

**Comment by paulogdm** [comment]
If you don't have a "builds" entry, it will consider your deployment as static, that is why you are observing your code being uploaded.
Take a look at our examples [here](https://github.com/zeit/now-examples).
