### ISSUE TITLE
misleading error when calling delete deployment and no deployment found 

### ISSUE THREAD

**Issue by kandros** [zeit/now-cloud#8]
https://api.zeit.co/now/deployments/xxxx

if a deployment with id 'xxxx' is not preset the error sent is:
```json
{
  "err": {
    "code": "authentication_error",
    "url": "https://zeit.co/errors/authentication_error",
    "message": "Not authorized"
  }
}
```

**Comment by OlliV** [comment]
I think the rationale is that the ID may or may not be a valid deployment ID and we don't want to leak that information. Of course we could also respond with 404 instead of 403.

**Comment by kandros** [comment]
Remember that responses from GET /now/deployments/xxxx  does clearly state that deployment xxxx is not present

**Comment by OlliV** [comment]
Fixed.
