### ISSUE TITLE
404 error if $ or %24 in request url

### ISSUE THREAD

**Issue by TNT-RoX** [zeit/now-cloud#84]
a $ or %24 in the url of a request to a deployment returns an unsolicited 404 error. The request never reaches the deployment.

now.json:
  `"builds":[
        {"src":"**/*.js","use":"@now/node"}
    ],
    "routes": [
        { "src": ".*", "dest": "/"}
    ]`

**Comment by williamli** [comment]
It's a known issue in our proxy / routing layer. Our team is working on resolving this.

**Comment by williamli** [comment]
This issue should be resolved now with https://github.com/zeit/now-proxy/pull/1153.

@TNT-RoX can you try again?

**Comment by williamli** [comment]
filed under https://github.com/zeit/now-builders/issues/523
